### PR TITLE
 fix(formatjs): Variable evaluate concatenation

### LINKED ISSUE #564: formatjs: defaultMessage does not handle statically evaluate-able variables
**Describe the bug**

formatjs leaves empty when there is a variable in the defaultMessage

**Example Input:**
```jsx
import { FormattedMessage, defineMessage, formatMessage } from "react-intl";

const hello = "Hello, ";
const world = "world!";

const helloWorldWithVariableConcatenation = defineMessage({
  defaultMessage: hello + world,
});
console.log(
  formatMessage(helloWorldWithVariableConcatenation),
);

function HelloWorldComponent() {
  return (
    <>
      <FormattedMessage defaultMessage={`${hello}${world}`} />
      <FormattedMessage defaultMessage={hello + world} />
    </>
  );
}

export default HelloWorldComponent;

```
**Current Output:**
```js
import { FormattedMessage, defineMessage, formatMessage } from "react-intl";
const hello = "Hello, ";
const world = "world!";
const helloWorldWithVariableConcatenation = defineMessage({
    id: "FZQkTV",
    defaultMessage: [
        {
            "type": 0,
            "value": "helloworld"
        }
    ]
});
console.log(formatMessage(helloWorldWithVariableConcatenation));
function HelloWorldComponent() {
    return React.createElement(React.Fragment, null, React.createElement(FormattedMessage, {
        defaultMessage: []
    }), React.createElement(FormattedMessage, {
        id: "FZQkTV",
        defaultMessage: [
            {
                "type": 0,
                "value": "helloworld"
            }
        ]
    }));
}
export default HelloWorldComponent;
```
**Expected Output:**
```js
import { FormattedMessage, defineMessage, formatMessage } from "react-intl";
const hello = "Hello, ";
const world = "world!";
const helloWorldWithVariableConcatenation = defineMessage({
    id: "wVJ82J",
    defaultMessage: [
        {
            "type": 0,
            "value": "Hello, world!"
        }
    ]
});
console.log(formatMessage(helloWorldWithVariableConcatenation));
function HelloWorldComponent() {
    return React.createElement(React.Fragment, null, React.createElement(FormattedMessage, {
        id: "wVJ82J",
        defaultMessage: [
            {
                "type": 0,
                "value": "Hello, world!"
            }
        ]
    }), React.createElement(FormattedMessage, {
        id: "wVJ82J",
        defaultMessage: [
            {
                "type": 0,
                "value": "Hello, world!"
            }
        ]
    }));
}
export default HelloWorldComponent;
```

### LINKED ISSUE #565: formatjs: doesn't throw an error if an identifier could not resolved
**Describe the bug**

It doesn't throw an error if an identifier could not resolved

**Example Input:**
```jsx
import { FormattedMessage, defineMessage, formatMessage } from "react-intl";

const hello = "Hello, ";
const world = "world!";

const helloWorldWithVariableConcatenation = defineMessage({
  defaultMessage: hello + world2,
});
console.log(
  formatMessage(helloWorldWithVariableConcatenation),
);

function HelloWorldComponent() {
  return (
    <>
      <FormattedMessage defaultMessage={hello + world2} />
    </>
  );
}

export default HelloWorldComponent;

```
**Current Output:**
```js
import { FormattedMessage, defineMessage, formatMessage } from "react-intl";
const hello = "Hello, ";
const world = "world!";
const helloWorldWithVariableConcatenation = defineMessage({
    id: "Y1Q9pi",
    defaultMessage: [
        {
            "type": 0,
            "value": "helloworld2"
        }
    ]
});
console.log(formatMessage(helloWorldWithVariableConcatenation));
function HelloWorldComponent() {
    return React.createElement(React.Fragment, null, React.createElement(FormattedMessage, {
        id: "Y1Q9pi",
        defaultMessage: [
            {
                "type": 0,
                "value": "helloworld2"
            }
        ]
    }));
}
export default HelloWorldComponent;
```
**Expected to emit an error:**

### LINKED ISSUE #566: formatjs: Can't evaluate template literal
**Describe the bug**

Can't evaluate template literal.

**Example Input:**
```jsx
import { FormattedMessage, defineMessage, formatMessage } from "react-intl";

const hello = "Hello";
const world = "world";

function HelloWorldComponent() {
  return (
    <>
      <FormattedMessage defaultMessage={`~${hello}, ${world}!`} />
    </>
  );
}

export default HelloWorldComponent;
```
**Current Output:**
```js
import { FormattedMessage } from "react-intl";
const hello = "Hello";
const world = "world";
function HelloWorldComponent() {
    return React.createElement(React.Fragment, null, React.createElement(FormattedMessage, {
        id: "0H4U/a",
        defaultMessage: [
            {
                "type": 0,
                "value": "~, !"
            }
        ]
    }));
}
export default HelloWorldComponent;

```
**Expected Output:**
```js
import { FormattedMessage } from "react-intl";
const hello = "Hello";
const world = "world";
function HelloWorldComponent() {
    return React.createElement(React.Fragment, null, React.createElement(FormattedMessage, {
        id: "0H4U/a",
        defaultMessage: [
            {
                "type": 0,
                "value": "~Hello, world!"
            }
        ]
    }));
}
export default HelloWorldComponent;

```

### PR DESCRIPTION
**Pull request by cuyl**
A huge refactor to improve variable evaluate for defaultMessage and description.

Fixes #564, Fixes #565, Fixes #566

### CODE REVIEW

**Comment by cuyl** [comment]
No worries, you can publish it and then upgrade swc_core in this branch.
@kdy1

File: packages/formatjs/src/lib.rs [hunk 1]
```diff
@@ -23,11 +24,14 @@ pub fn process(mut program: Program, metadata: TransformPluginProgramMetadata) -
         Default::default()
     };
 
+    let module = program.as_module().unwrap();
```
Comment (kdy1) [inline packages/formatjs/src/lib.rs]: Can you use `if let else` to return the `Program::Script` as-is to avoid panic?

Comment (cuyl) [reply packages/formatjs/src/lib.rs]: OK, Solved in 8085c158512812657cc9e008a20d88fc59077e37
